### PR TITLE
v0.5.0 - Discharge conversions

### PR DESCRIPTION
**Pull request by engrleir**
as per roadmap for version 0.5.0, Added discharge conversions from cubic meters per second to cubic feet per second.

Please comment what other conversions are needed.

Thanks.

### CODE REVIEW

**Comment by alexiusacademia** [comment]
If possible, please let us add **liters per second**.

Thanks

**Comment by engrleir** [comment]
Added liter per second unit conversions.

**Comment by alexiusacademia** [comment]
In the test, the following are observed:

- _Testing for lps->cfs_
    - `2.5 l/s` should result in `0.088 cfs`, in the test, the checking was with `88286.7`
- _Testing for cfs->lps_
    - `2.5 cfs` should result in `70.7921 cfs`, in the test, the checking was with `0.0000708`
- There should be 9 tests total based on the `conversionFactors`. 3 units with 3 conversions each.

**Comment by engrleir** [comment]
The following were fixed:
- correct conversion factors between lfs and cfs implemented
- additional test case added.

**Pull request merged**
